//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef OCL_OCLCSPACKAGE_HPP
#define OCL_OCLCSPACKAGE_HPP

#include "ecore/EPackage.hpp"

namespace ecore 
{
}

namespace ocl::OclCS 
{

}

namespace ocl::OclCS 
{
	/*!
	The Metamodel Package for the OclCS metamodel. This package is used to enable the reflection of model elements. It contains all model elements
	which were described in an ecore file.
	*/
	/*!
	 */
	class OclCSPackage : virtual public ecore::EPackage 
	{
		private:    
			OclCSPackage(OclCSPackage const&) = delete;
			OclCSPackage& operator=(OclCSPackage const&) = delete;

		protected:
			OclCSPackage(){}

		public:
			//static variables
			static const std::string eNAME;
			static const std::string eNS_URI;
			static const std::string eNS_PREFIX;

			
			

			

			//Singleton Instance and Getter
			private:
				static std::shared_ptr<OclCSPackage> instance;
			public:
				static std::shared_ptr<OclCSPackage> eInstance();
	};
}
#endif /* end of include guard: OCL_OCLCSPACKAGE_HPP */
