//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef OCLFACTORYIMPL_HPP
#define OCLFACTORYIMPL_HPP

#include "ecore/impl/EFactoryImpl.hpp"

#include "ocl/OclFactory.hpp"

namespace ocl 
{
}

namespace ocl 
{
	class OclFactoryImpl : virtual public ecore::EFactoryImpl , virtual public OclFactory 
	{
		private:    
			OclFactoryImpl(OclFactoryImpl const&) = delete;
			OclFactoryImpl& operator=(OclFactoryImpl const&) = delete;

		protected:
			friend class OclFactory;
			// Constructor
			OclFactoryImpl();

		public:
			virtual ~OclFactoryImpl();
			virtual std::shared_ptr<ecore::EObject> create(std::string _className,  std::shared_ptr<ecore::EObject> container=nullptr, const int referenceID = -1) const;
			virtual std::shared_ptr<ecore::EObject> create(const int classID,  std::shared_ptr<ecore::EObject> container = nullptr, const int referenceID = -1) const;
			virtual std::shared_ptr<ecore::EObject> create(std::shared_ptr<ecore::EClass> _class, std::shared_ptr<EObject> _container=nullptr, const int referenceID = -1) const;

			//Creator functions
			 

		private:
			static OclFactory* create();
            std::map<std::string,int> m_idMap;
	};
}
#endif /* end of include guard: OCLFACTORYIMPL_HPP */
