//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef OCLPACKAGEIMPL_HPP
#define OCLPACKAGEIMPL_HPP

#include "ecore/EcorePackage.hpp"
#include "ecore/impl/EPackageImpl.hpp"

#include "ocl/OclPackage.hpp" 


namespace ocl 
{
	namespace Evaluations 
	{
		class EvaluationsPackage;
	}

	namespace Expressions 
	{
		class ExpressionsPackage;
	}

	namespace OclCS 
	{
		class OclCSPackage;
	}

	namespace Types 
	{
		class TypesPackage;
	}

	namespace Utilities 
	{
		class UtilitiesPackage;
	}

	namespace Values 
	{
		class ValuesPackage;
	}
}

namespace ecore
{
	class EcoreFactory;
}

namespace ocl
{
	class OclPackageImpl : public ecore::EPackageImpl ,virtual public OclPackage
	{
		private:    
			OclPackageImpl(OclPackageImpl const&) = delete;
			OclPackageImpl& operator=(OclPackageImpl const&) = delete;

		protected:
			OclPackageImpl();

		public:
			virtual ~OclPackageImpl();


			
			// SubPackages Getters
			virtual std::shared_ptr<Evaluations::EvaluationsPackage> getEvaluations_Package() const ;
			virtual std::shared_ptr<Expressions::ExpressionsPackage> getExpressions_Package() const ;
			virtual std::shared_ptr<OclCS::OclCSPackage> getOclCS_Package() const ;
			virtual std::shared_ptr<Types::TypesPackage> getTypes_Package() const ;
			virtual std::shared_ptr<Utilities::UtilitiesPackage> getUtilities_Package() const ;
			virtual std::shared_ptr<Values::ValuesPackage> getValues_Package() const ;
			

		private:
			
			
			
			
			

			friend class OclPackage;

			static bool isInited;
			static OclPackage* create();
			bool isInitialized = false;
 			bool isCreated = false;

			virtual void init(std::shared_ptr<ecore::EPackage> package);

		public:
			void createPackageContents(std::shared_ptr<ecore::EPackage> package);
			void initializePackageContents();

		private:
			void createPackageEDataTypes(std::shared_ptr<ecore::EPackage> package, std::shared_ptr<ecore::EcoreFactory> factory);

			void initializePackageEDataTypes();



	};
}
#endif /* end of include guard: OCLPACKAGEIMPL_HPP */
