//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef OCL_EVALUATIONS_TUPLELITERALEXPEVAL_HPP
#define OCL_EVALUATIONS_TUPLELITERALEXPEVAL_HPP

#include <list>
#include <memory>
#include <string>


// forward declarations
template<class T> class Bag; 



//*********************************
// generated Includes

#include <map>

namespace persistence
{
	namespace interfaces
	{
		class XLoadHandler; // used for Persistence
		class XSaveHandler; // used for Persistence
	}
}

namespace ocl
{
	class OclFactory;
}

//Forward Declaration for used types
namespace ocl::Evaluations 
{
	class EvalEnvironment;
}

namespace ocl::Evaluations 
{
	class LiteralExpEval;
}

namespace fUML::Semantics::Loci 
{
	class Locus;
}

namespace ocl::Expressions 
{
	class OclExpression;
}

namespace fUML::Semantics::Values 
{
	class Value;
}

namespace uml 
{
	class ValueSpecification;
}

namespace ocl::Evaluations 
{
	class VariableDeclEval;
}

// base class includes
#include "ocl/Evaluations/LiteralExpEval.hpp"

// enum includes


//*********************************
namespace ocl::Evaluations 
{
	/*!
	 */
	class TupleLiteralExpEval:virtual public LiteralExpEval
	{
		public:
 			TupleLiteralExpEval(const TupleLiteralExpEval &) {}
			TupleLiteralExpEval& operator=(TupleLiteralExpEval const&) = delete;

		protected:
			TupleLiteralExpEval(){}


		public:
			virtual std::shared_ptr<ecore::EObject> copy() const = 0;

			//destructor
			virtual ~TupleLiteralExpEval() {}

			//*********************************
			// Operations
			//*********************************
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			//*********************************
			// Reference
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<Bag<ocl::Evaluations::VariableDeclEval>> getTuplePart() const = 0;
			
			

		protected:
			//*********************************
			// Attribute Members
			//*********************************
			
			
			//*********************************
			// Reference Members
			//*********************************
			/*!
			 */
			std::shared_ptr<Bag<ocl::Evaluations::VariableDeclEval>> m_tuplePart;
			

		public:
			//*********************************
			// Union Getter
			//*********************************
			

			virtual std::shared_ptr<ecore::EObject> eContainer() const = 0; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) = 0;
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) = 0;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const = 0;
			
	};

}
#endif /* end of include guard: OCL_EVALUATIONS_TUPLELITERALEXPEVAL_HPP */
