//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef OCL_EVALUATIONS_VARIABLEDECLEVAL_HPP
#define OCL_EVALUATIONS_VARIABLEDECLEVAL_HPP

#include <list>
#include <memory>
#include <string>


// forward declarations



//*********************************
// generated Includes

#include <map>

namespace persistence
{
	namespace interfaces
	{
		class XLoadHandler; // used for Persistence
		class XSaveHandler; // used for Persistence
	}
}

namespace ocl
{
	class OclFactory;
}

//Forward Declaration for used types
namespace ocl::Evaluations 
{
	class OclExpEval;
}

namespace fUML::Semantics::SimpleClassifiers 
{
	class StringValue;
}

// base class includes

// enum includes

#include "ecore/EObject.hpp"

//*********************************
namespace ocl::Evaluations 
{
	/*!
	 */
	class VariableDeclEval : virtual public ecore::EObject 

	{
		public:
 			VariableDeclEval(const VariableDeclEval &) {}
			VariableDeclEval& operator=(VariableDeclEval const&) = delete;

		protected:
			VariableDeclEval(){}


		public:
			virtual std::shared_ptr<ecore::EObject> copy() const = 0;

			//destructor
			virtual ~VariableDeclEval() {}

			//*********************************
			// Operations
			//*********************************
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			//*********************************
			// Reference
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<ocl::Evaluations::OclExpEval > getInitExp() const = 0;
			
			/*!
			 */
			virtual void setInitExp(std::shared_ptr<ocl::Evaluations::OclExpEval> _initExp_initExp) = 0;
			/*!
			 */
			virtual std::shared_ptr<fUML::Semantics::SimpleClassifiers::StringValue > getName() const = 0;
			
			/*!
			 */
			virtual void setName(std::shared_ptr<fUML::Semantics::SimpleClassifiers::StringValue> _name_name) = 0;
			

		protected:
			//*********************************
			// Attribute Members
			//*********************************
			
			
			//*********************************
			// Reference Members
			//*********************************
			/*!
			 */
			std::shared_ptr<ocl::Evaluations::OclExpEval > m_initExp;
			/*!
			 */
			std::shared_ptr<fUML::Semantics::SimpleClassifiers::StringValue > m_name;
			

		public:
			//*********************************
			// Union Getter
			//*********************************
			

			virtual std::shared_ptr<ecore::EObject> eContainer() const = 0; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) = 0;
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) = 0;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const = 0;
			
	};

}
#endif /* end of include guard: OCL_EVALUATIONS_VARIABLEDECLEVAL_HPP */
