//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef OCL_EXPRESSIONS_COLLECTIONLITERALPARTCOLLECTIONLITERALPARTIMPL_HPP
#define OCL_EXPRESSIONS_COLLECTIONLITERALPARTCOLLECTIONLITERALPARTIMPL_HPP

//*********************************
// generated Includes

//Model includes
#include "../CollectionLiteralPart.hpp"

#include "ocl/Expressions/impl/ExpressionsFactoryImpl.hpp"
#include "ecore/impl/ETypedElementImpl.hpp"

//*********************************
namespace ocl::Expressions 
{
	class CollectionLiteralPartImpl :virtual public ecore::ETypedElementImpl, virtual public CollectionLiteralPart 
	{
		public: 
			CollectionLiteralPartImpl(const CollectionLiteralPartImpl & obj);
			virtual std::shared_ptr<ecore::EObject> copy() const;

		private:    
			CollectionLiteralPartImpl& operator=(CollectionLiteralPartImpl const&) = delete;

		protected:
			friend class ocl::Expressions::ExpressionsFactoryImpl;
			CollectionLiteralPartImpl();
			virtual std::shared_ptr<CollectionLiteralPart> getThisCollectionLiteralPartPtr() const;
			virtual void setThisCollectionLiteralPartPtr(std::weak_ptr<CollectionLiteralPart> thisCollectionLiteralPartPtr);

			//Additional constructors for the containments back reference
			CollectionLiteralPartImpl(std::weak_ptr<ecore::EObject > par_eContainer);




		public:
			//destructor
			virtual ~CollectionLiteralPartImpl();
			
			//*********************************
			// Operations
			//*********************************
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			
			//*********************************
			// Reference
			//*********************************
							
			
			//*********************************
			// Union Getter
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<Union<ecore::EObject>> getEContens() const ; 
			 
			//*********************************
			// Structural Feature Getter/Setter
			//*********************************

			virtual std::shared_ptr<ecore::EObject> eContainer() const ; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) ;
			virtual void loadAttributes(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::map<std::string, std::string> attr_list);
			virtual void loadNode(std::string nodeName, std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler);
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) ;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const ;
			virtual void saveContent(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const;
			

		protected:
			virtual std::shared_ptr<ecore::EClass> eStaticClass() const;
			virtual Any eGet(int featureID, bool resolve, bool coreType) const ;
			virtual bool internalEIsSet(int featureID) const ;
			virtual bool eSet(int featureID, Any newValue) ;

		private:
			std::weak_ptr<CollectionLiteralPart> m_thisCollectionLiteralPartPtr;
	};
}
#endif /* end of include guard: OCL_EXPRESSIONS_COLLECTIONLITERALPARTCOLLECTIONLITERALPARTIMPL_HPP */
