//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef OCL_EXPRESSIONS_TUPLELITERALPARTTUPLELITERALPARTIMPL_HPP
#define OCL_EXPRESSIONS_TUPLELITERALPARTTUPLELITERALPARTIMPL_HPP

//*********************************
// generated Includes

//Model includes
#include "../TupleLiteralPart.hpp"

#include "ocl/Expressions/impl/ExpressionsFactoryImpl.hpp"
#include "ecore/impl/ETypedElementImpl.hpp"

//*********************************
namespace ocl::Expressions 
{
	class TupleLiteralPartImpl :virtual public ecore::ETypedElementImpl, virtual public TupleLiteralPart 
	{
		public: 
			TupleLiteralPartImpl(const TupleLiteralPartImpl & obj);
			virtual std::shared_ptr<ecore::EObject> copy() const;

		private:    
			TupleLiteralPartImpl& operator=(TupleLiteralPartImpl const&) = delete;

		protected:
			friend class ocl::Expressions::ExpressionsFactoryImpl;
			TupleLiteralPartImpl();
			virtual std::shared_ptr<TupleLiteralPart> getThisTupleLiteralPartPtr() const;
			virtual void setThisTupleLiteralPartPtr(std::weak_ptr<TupleLiteralPart> thisTupleLiteralPartPtr);

			//Additional constructors for the containments back reference
			TupleLiteralPartImpl(std::weak_ptr<ecore::EObject > par_eContainer);




		public:
			//destructor
			virtual ~TupleLiteralPartImpl();
			
			//*********************************
			// Operations
			//*********************************
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			
			//*********************************
			// Reference
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<ecore::EAttribute > getAttribute() const ;
			
			/*!
			 */
			virtual void setAttribute(std::shared_ptr<ecore::EAttribute> _attribute_attribute) ;
							
			
			//*********************************
			// Union Getter
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<Union<ecore::EObject>> getEContens() const ; 
			 
			//*********************************
			// Structural Feature Getter/Setter
			//*********************************

			virtual std::shared_ptr<ecore::EObject> eContainer() const ; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) ;
			virtual void loadAttributes(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::map<std::string, std::string> attr_list);
			virtual void loadNode(std::string nodeName, std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler);
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) ;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const ;
			virtual void saveContent(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const;
			

		protected:
			virtual std::shared_ptr<ecore::EClass> eStaticClass() const;
			virtual Any eGet(int featureID, bool resolve, bool coreType) const ;
			virtual bool internalEIsSet(int featureID) const ;
			virtual bool eSet(int featureID, Any newValue) ;

		private:
			std::weak_ptr<TupleLiteralPart> m_thisTupleLiteralPartPtr;
	};
}
#endif /* end of include guard: OCL_EXPRESSIONS_TUPLELITERALPARTTUPLELITERALPARTIMPL_HPP */
