//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef OCL_EXPRESSIONS_COLLECTIONRANGE_HPP
#define OCL_EXPRESSIONS_COLLECTIONRANGE_HPP

#include <list>
#include <memory>
#include <string>


// forward declarations



//*********************************
// generated Includes

#include <map>

namespace persistence
{
	namespace interfaces
	{
		class XLoadHandler; // used for Persistence
		class XSaveHandler; // used for Persistence
	}
}

namespace ocl
{
	class OclFactory;
}

//Forward Declaration for used types
namespace ocl::Expressions 
{
	class CollectionLiteralPart;
}

namespace ecore 
{
	class EAnnotation;
}

namespace ecore 
{
	class EClassifier;
}

namespace ecore 
{
	class EGenericType;
}

namespace ecore 
{
	class EObject;
}

namespace ocl::Expressions 
{
	class OclExpression;
}

// base class includes
#include "ocl/Expressions/CollectionLiteralPart.hpp"

// enum includes


//*********************************
namespace ocl::Expressions 
{
	/*!
	 */
	class CollectionRange:virtual public CollectionLiteralPart
	{
		public:
 			CollectionRange(const CollectionRange &) {}
			CollectionRange& operator=(CollectionRange const&) = delete;

		protected:
			CollectionRange(){}


		public:
			virtual std::shared_ptr<ecore::EObject> copy() const = 0;

			//destructor
			virtual ~CollectionRange() {}

			//*********************************
			// Operations
			//*********************************
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			//*********************************
			// Reference
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<ocl::Expressions::OclExpression > getFirst() const = 0;
			
			/*!
			 */
			virtual void setFirst(std::shared_ptr<ocl::Expressions::OclExpression> _first_first) = 0;
			/*!
			 */
			virtual std::shared_ptr<ocl::Expressions::OclExpression > getLast() const = 0;
			
			/*!
			 */
			virtual void setLast(std::shared_ptr<ocl::Expressions::OclExpression> _last_last) = 0;
			

		protected:
			//*********************************
			// Attribute Members
			//*********************************
			
			
			//*********************************
			// Reference Members
			//*********************************
			/*!
			 */
			std::shared_ptr<ocl::Expressions::OclExpression > m_first;
			/*!
			 */
			std::shared_ptr<ocl::Expressions::OclExpression > m_last;
			

		public:
			//*********************************
			// Union Getter
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<Union<ecore::EObject>> getEContens() const = 0;

			virtual std::shared_ptr<ecore::EObject> eContainer() const = 0; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) = 0;
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) = 0;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const = 0;
			
	};

}
#endif /* end of include guard: OCL_EXPRESSIONS_COLLECTIONRANGE_HPP */
