//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef OCL_EXPRESSIONSPACKAGE_HPP
#define OCL_EXPRESSIONSPACKAGE_HPP

#include "ecore/EPackage.hpp"

namespace ecore 
{
	class EAttribute;
	class EClass;
	class EDataType;
	class EEnum;
	class EEnumLiteral;
	class EGenericType;
	class EReference;
}

namespace ocl::Expressions 
{
	class AssociationClassCallExp;
	class BooleanLiteralExp;
	class CallExp;
	class CollectionItem;
	class CollectionLiteralExp;
	class CollectionLiteralPart;
	class CollectionRange;
	class EnumLiteralExp;
	class ExpressionInOcl;
	class FeatureCallExp;
	class IfExp;
	class InfixedExp;
	class IntegerLiteralExp;
	class InvalidLiteralExp;
	class IterateExp;
	class IteratorExp;
	class LetExp;
	class LiteralExp;
	class LoopExp;
	class MessageExp;
	class NavigationCallExp;
	class NullLiteralExp;
	class NumericLiteralExp;
	class OclExpression;
	class OperationCallExp;
	class PrimitiveLiteralExp;
	class PropertyCallExp;
	class RealLiteralExp;
	class StateExp;
	class StringLiteralExp;
	class TupleLiteralExp;
	class TupleLiteralPart;
	class TypeExp;
	class UnlimitedNaturalExp;
	class UnspecifiedValueExp;
	class Variable;
	class VariableExp;
}

namespace ocl::Expressions 
{
	/*!
	The Metamodel Package for the Expressions metamodel. This package is used to enable the reflection of model elements. It contains all model elements
	which were described in an ecore file.
	*/
	/*!
	 */
	class ExpressionsPackage : virtual public ecore::EPackage 
	{
		private:    
			ExpressionsPackage(ExpressionsPackage const&) = delete;
			ExpressionsPackage& operator=(ExpressionsPackage const&) = delete;

		protected:
			ExpressionsPackage(){}

		public:
			//static variables
			static const std::string eNAME;
			static const std::string eNS_URI;
			static const std::string eNS_PREFIX;

			// Begin Class AssociationClassCallExp
			//Class and Feature IDs 
			static const unsigned int ASSOCIATIONCLASSCALLEXP_CLASS = 2;
			static const unsigned int ASSOCIATIONCLASSCALLEXP_CLASS_FEATURE_COUNT = 30;
			static const unsigned int ASSOCIATIONCLASSCALLEXP_CLASS_OPERATION_COUNT = 16;
			
			static const int ASSOCIATIONCLASSCALLEXP_ATTRIBUTE_REFERREDASSOCIATIONCLASS = 229;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getAssociationClassCallExp_Class() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getAssociationClassCallExp_Attribute_referredAssociationClass() const = 0;
			
			
			// End Class AssociationClassCallExp


			// Begin Class BooleanLiteralExp
			//Class and Feature IDs 
			static const unsigned int BOOLEANLITERALEXP_CLASS = 8;
			static const unsigned int BOOLEANLITERALEXP_CLASS_FEATURE_COUNT = 27;
			static const unsigned int BOOLEANLITERALEXP_CLASS_OPERATION_COUNT = 16;
			static const int BOOLEANLITERALEXP_ATTRIBUTE_BOOLEANSYMBOL = 826;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getBooleanLiteralExp_Class() const = 0;
			
			virtual std::shared_ptr<ecore::EAttribute> getBooleanLiteralExp_Attribute_booleanSymbol() const = 0;
			
			
			
			// End Class BooleanLiteralExp


			// Begin Class CallExp
			//Class and Feature IDs 
			static const unsigned int CALLEXP_CLASS = 10;
			static const unsigned int CALLEXP_CLASS_FEATURE_COUNT = 26;
			static const unsigned int CALLEXP_CLASS_OPERATION_COUNT = 16;
			
			static const int CALLEXP_ATTRIBUTE_SOURCE = 1025;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getCallExp_Class() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getCallExp_Attribute_source() const = 0;
			
			
			// End Class CallExp


			// Begin Class CollectionItem
			//Class and Feature IDs 
			static const unsigned int COLLECTIONITEM_CLASS = 11;
			static const unsigned int COLLECTIONITEM_CLASS_FEATURE_COUNT = 14;
			static const unsigned int COLLECTIONITEM_CLASS_OPERATION_COUNT = 16;
			
			static const int COLLECTIONITEM_ATTRIBUTE_ITEM = 1113;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getCollectionItem_Class() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getCollectionItem_Attribute_item() const = 0;
			
			
			// End Class CollectionItem


			// Begin Class CollectionLiteralExp
			//Class and Feature IDs 
			static const unsigned int COLLECTIONLITERALEXP_CLASS = 14;
			static const unsigned int COLLECTIONLITERALEXP_CLASS_FEATURE_COUNT = 27;
			static const unsigned int COLLECTIONLITERALEXP_CLASS_OPERATION_COUNT = 16;
			static const int COLLECTIONLITERALEXP_ATTRIBUTE_KIND = 1425;
			
			static const int COLLECTIONLITERALEXP_ATTRIBUTE_PART = 1426;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getCollectionLiteralExp_Class() const = 0;
			
			virtual std::shared_ptr<ecore::EAttribute> getCollectionLiteralExp_Attribute_kind() const = 0;
			
			virtual std::shared_ptr<ecore::EReference> getCollectionLiteralExp_Attribute_part() const = 0;
			
			
			// End Class CollectionLiteralExp


			// Begin Class CollectionLiteralPart
			//Class and Feature IDs 
			static const unsigned int COLLECTIONLITERALPART_CLASS = 16;
			static const unsigned int COLLECTIONLITERALPART_CLASS_FEATURE_COUNT = 13;
			static const unsigned int COLLECTIONLITERALPART_CLASS_OPERATION_COUNT = 16;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getCollectionLiteralPart_Class() const = 0;
			
			
			
			
			// End Class CollectionLiteralPart


			// Begin Class CollectionRange
			//Class and Feature IDs 
			static const unsigned int COLLECTIONRANGE_CLASS = 18;
			static const unsigned int COLLECTIONRANGE_CLASS_FEATURE_COUNT = 15;
			static const unsigned int COLLECTIONRANGE_CLASS_OPERATION_COUNT = 16;
			
			static const int COLLECTIONRANGE_ATTRIBUTE_FIRST = 1813;
			static const int COLLECTIONRANGE_ATTRIBUTE_LAST = 1814;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getCollectionRange_Class() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getCollectionRange_Attribute_first() const = 0;
			virtual std::shared_ptr<ecore::EReference> getCollectionRange_Attribute_last() const = 0;
			
			
			// End Class CollectionRange


			// Begin Class EnumLiteralExp
			//Class and Feature IDs 
			static const unsigned int ENUMLITERALEXP_CLASS = 23;
			static const unsigned int ENUMLITERALEXP_CLASS_FEATURE_COUNT = 26;
			static const unsigned int ENUMLITERALEXP_CLASS_OPERATION_COUNT = 16;
			
			static const int ENUMLITERALEXP_ATTRIBUTE_REFERREDENUMLITERAL = 2325;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getEnumLiteralExp_Class() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getEnumLiteralExp_Attribute_referredEnumLiteral() const = 0;
			
			
			// End Class EnumLiteralExp


			// Begin Class ExpressionInOcl
			//Class and Feature IDs 
			static const unsigned int EXPRESSIONINOCL_CLASS = 27;
			static const unsigned int EXPRESSIONINOCL_CLASS_FEATURE_COUNT = 17;
			static const unsigned int EXPRESSIONINOCL_CLASS_OPERATION_COUNT = 16;
			
			static const int EXPRESSIONINOCL_ATTRIBUTE_BODYEXPRESSION = 2713;
			static const int EXPRESSIONINOCL_ATTRIBUTE_CONTEXTVARIABLE = 2714;
			static const int EXPRESSIONINOCL_ATTRIBUTE_PARAMETERVARIABLE = 2716;
			static const int EXPRESSIONINOCL_ATTRIBUTE_RESULTVARIABLE = 2715;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getExpressionInOcl_Class() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getExpressionInOcl_Attribute_bodyExpression() const = 0;
			virtual std::shared_ptr<ecore::EReference> getExpressionInOcl_Attribute_contextVariable() const = 0;
			virtual std::shared_ptr<ecore::EReference> getExpressionInOcl_Attribute_parameterVariable() const = 0;
			virtual std::shared_ptr<ecore::EReference> getExpressionInOcl_Attribute_resultVariable() const = 0;
			
			
			// End Class ExpressionInOcl


			// Begin Class FeatureCallExp
			//Class and Feature IDs 
			static const unsigned int FEATURECALLEXP_CLASS = 29;
			static const unsigned int FEATURECALLEXP_CLASS_FEATURE_COUNT = 27;
			static const unsigned int FEATURECALLEXP_CLASS_OPERATION_COUNT = 16;
			static const int FEATURECALLEXP_ATTRIBUTE_ISPRE = 2926;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getFeatureCallExp_Class() const = 0;
			
			virtual std::shared_ptr<ecore::EAttribute> getFeatureCallExp_Attribute_isPre() const = 0;
			
			
			
			// End Class FeatureCallExp


			// Begin Class IfExp
			//Class and Feature IDs 
			static const unsigned int IFEXP_CLASS = 30;
			static const unsigned int IFEXP_CLASS_FEATURE_COUNT = 28;
			static const unsigned int IFEXP_CLASS_OPERATION_COUNT = 16;
			
			static const int IFEXP_ATTRIBUTE_CONDITION = 3025;
			static const int IFEXP_ATTRIBUTE_ELSEEXPRESSION = 3027;
			static const int IFEXP_ATTRIBUTE_THENEXPRESSION = 3026;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getIfExp_Class() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getIfExp_Attribute_condition() const = 0;
			virtual std::shared_ptr<ecore::EReference> getIfExp_Attribute_elseExpression() const = 0;
			virtual std::shared_ptr<ecore::EReference> getIfExp_Attribute_thenExpression() const = 0;
			
			
			// End Class IfExp


			// Begin Class InfixedExp
			//Class and Feature IDs 
			static const unsigned int INFIXEDEXP_CLASS = 32;
			static const unsigned int INFIXEDEXP_CLASS_FEATURE_COUNT = 26;
			static const unsigned int INFIXEDEXP_CLASS_OPERATION_COUNT = 16;
			
			static const int INFIXEDEXP_ATTRIBUTE_SOURCE = 3225;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getInfixedExp_Class() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getInfixedExp_Attribute_source() const = 0;
			
			
			// End Class InfixedExp


			// Begin Class IntegerLiteralExp
			//Class and Feature IDs 
			static const unsigned int INTEGERLITERALEXP_CLASS = 33;
			static const unsigned int INTEGERLITERALEXP_CLASS_FEATURE_COUNT = 27;
			static const unsigned int INTEGERLITERALEXP_CLASS_OPERATION_COUNT = 16;
			static const int INTEGERLITERALEXP_ATTRIBUTE_INTEGERSYMBOL = 3326;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getIntegerLiteralExp_Class() const = 0;
			
			virtual std::shared_ptr<ecore::EAttribute> getIntegerLiteralExp_Attribute_integerSymbol() const = 0;
			
			
			
			// End Class IntegerLiteralExp


			// Begin Class InvalidLiteralExp
			//Class and Feature IDs 
			static const unsigned int INVALIDLITERALEXP_CLASS = 35;
			static const unsigned int INVALIDLITERALEXP_CLASS_FEATURE_COUNT = 25;
			static const unsigned int INVALIDLITERALEXP_CLASS_OPERATION_COUNT = 16;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getInvalidLiteralExp_Class() const = 0;
			
			
			
			
			// End Class InvalidLiteralExp


			// Begin Class IterateExp
			//Class and Feature IDs 
			static const unsigned int ITERATEEXP_CLASS = 37;
			static const unsigned int ITERATEEXP_CLASS_FEATURE_COUNT = 29;
			static const unsigned int ITERATEEXP_CLASS_OPERATION_COUNT = 16;
			
			static const int ITERATEEXP_ATTRIBUTE_RESULT = 3728;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getIterateExp_Class() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getIterateExp_Attribute_result() const = 0;
			
			
			// End Class IterateExp


			// Begin Class IteratorExp
			//Class and Feature IDs 
			static const unsigned int ITERATOREXP_CLASS = 39;
			static const unsigned int ITERATOREXP_CLASS_FEATURE_COUNT = 28;
			static const unsigned int ITERATOREXP_CLASS_OPERATION_COUNT = 16;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getIteratorExp_Class() const = 0;
			
			
			
			
			// End Class IteratorExp


			// Begin Class LetExp
			//Class and Feature IDs 
			static const unsigned int LETEXP_CLASS = 41;
			static const unsigned int LETEXP_CLASS_FEATURE_COUNT = 27;
			static const unsigned int LETEXP_CLASS_OPERATION_COUNT = 16;
			
			static const int LETEXP_ATTRIBUTE_IN = 4125;
			static const int LETEXP_ATTRIBUTE_VARIABLE = 4126;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getLetExp_Class() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getLetExp_Attribute_in() const = 0;
			virtual std::shared_ptr<ecore::EReference> getLetExp_Attribute_variable() const = 0;
			
			
			// End Class LetExp


			// Begin Class LiteralExp
			//Class and Feature IDs 
			static const unsigned int LITERALEXP_CLASS = 43;
			static const unsigned int LITERALEXP_CLASS_FEATURE_COUNT = 25;
			static const unsigned int LITERALEXP_CLASS_OPERATION_COUNT = 16;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getLiteralExp_Class() const = 0;
			
			
			
			
			// End Class LiteralExp


			// Begin Class LoopExp
			//Class and Feature IDs 
			static const unsigned int LOOPEXP_CLASS = 46;
			static const unsigned int LOOPEXP_CLASS_FEATURE_COUNT = 28;
			static const unsigned int LOOPEXP_CLASS_OPERATION_COUNT = 16;
			
			static const int LOOPEXP_ATTRIBUTE_BODY = 4626;
			static const int LOOPEXP_ATTRIBUTE_ITERATOR = 4627;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getLoopExp_Class() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getLoopExp_Attribute_body() const = 0;
			virtual std::shared_ptr<ecore::EReference> getLoopExp_Attribute_iterator() const = 0;
			
			
			// End Class LoopExp


			// Begin Class MessageExp
			//Class and Feature IDs 
			static const unsigned int MESSAGEEXP_CLASS = 48;
			static const unsigned int MESSAGEEXP_CLASS_FEATURE_COUNT = 29;
			static const unsigned int MESSAGEEXP_CLASS_OPERATION_COUNT = 16;
			
			static const int MESSAGEEXP_ATTRIBUTE_ARGUMENT = 4826;
			static const int MESSAGEEXP_ATTRIBUTE_CALLEDOPERATION = 4827;
			static const int MESSAGEEXP_ATTRIBUTE_SENTSIGNAL = 4828;
			static const int MESSAGEEXP_ATTRIBUTE_TARGET = 4825;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getMessageExp_Class() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getMessageExp_Attribute_argument() const = 0;
			virtual std::shared_ptr<ecore::EReference> getMessageExp_Attribute_calledOperation() const = 0;
			virtual std::shared_ptr<ecore::EReference> getMessageExp_Attribute_sentSignal() const = 0;
			virtual std::shared_ptr<ecore::EReference> getMessageExp_Attribute_target() const = 0;
			
			
			// End Class MessageExp


			// Begin Class NavigationCallExp
			//Class and Feature IDs 
			static const unsigned int NAVIGATIONCALLEXP_CLASS = 53;
			static const unsigned int NAVIGATIONCALLEXP_CLASS_FEATURE_COUNT = 29;
			static const unsigned int NAVIGATIONCALLEXP_CLASS_OPERATION_COUNT = 16;
			
			static const int NAVIGATIONCALLEXP_ATTRIBUTE_NAVIGATIONSOURCE = 5328;
			static const int NAVIGATIONCALLEXP_ATTRIBUTE_QUALIFIER = 5327;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getNavigationCallExp_Class() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getNavigationCallExp_Attribute_navigationSource() const = 0;
			virtual std::shared_ptr<ecore::EReference> getNavigationCallExp_Attribute_qualifier() const = 0;
			
			
			// End Class NavigationCallExp


			// Begin Class NullLiteralExp
			//Class and Feature IDs 
			static const unsigned int NULLLITERALEXP_CLASS = 55;
			static const unsigned int NULLLITERALEXP_CLASS_FEATURE_COUNT = 26;
			static const unsigned int NULLLITERALEXP_CLASS_OPERATION_COUNT = 16;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getNullLiteralExp_Class() const = 0;
			
			
			
			
			// End Class NullLiteralExp


			// Begin Class NumericLiteralExp
			//Class and Feature IDs 
			static const unsigned int NUMERICLITERALEXP_CLASS = 56;
			static const unsigned int NUMERICLITERALEXP_CLASS_FEATURE_COUNT = 26;
			static const unsigned int NUMERICLITERALEXP_CLASS_OPERATION_COUNT = 16;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getNumericLiteralExp_Class() const = 0;
			
			
			
			
			// End Class NumericLiteralExp


			// Begin Class OclExpression
			//Class and Feature IDs 
			static const unsigned int OCLEXPRESSION_CLASS = 60;
			static const unsigned int OCLEXPRESSION_CLASS_FEATURE_COUNT = 25;
			static const unsigned int OCLEXPRESSION_CLASS_OPERATION_COUNT = 16;
			
			static const int OCLEXPRESSION_ATTRIBUTE_APPLIEDELEMENT = 6013;
			static const int OCLEXPRESSION_ATTRIBUTE_ELSEOWNER = 6020;
			static const int OCLEXPRESSION_ATTRIBUTE_FIRSTOWNER = 6022;
			static const int OCLEXPRESSION_ATTRIBUTE_IFOWNER = 6019;
			static const int OCLEXPRESSION_ATTRIBUTE_INITIALIZEDELEMENT = 6015;
			static const int OCLEXPRESSION_ATTRIBUTE_INSTANCE = 6024;
			static const int OCLEXPRESSION_ATTRIBUTE_LASTOWNER = 6023;
			static const int OCLEXPRESSION_ATTRIBUTE_LOOPBODYOWNER = 6014;
			static const int OCLEXPRESSION_ATTRIBUTE_PARENTCALL = 6017;
			static const int OCLEXPRESSION_ATTRIBUTE_PARENTNAV = 6021;
			static const int OCLEXPRESSION_ATTRIBUTE_THENOWNER = 6018;
			static const int OCLEXPRESSION_ATTRIBUTE_TOPEXPRESSION = 6016;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getOclExpression_Class() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getOclExpression_Attribute_appliedElement() const = 0;
			virtual std::shared_ptr<ecore::EReference> getOclExpression_Attribute_elseOwner() const = 0;
			virtual std::shared_ptr<ecore::EReference> getOclExpression_Attribute_firstOwner() const = 0;
			virtual std::shared_ptr<ecore::EReference> getOclExpression_Attribute_ifOwner() const = 0;
			virtual std::shared_ptr<ecore::EReference> getOclExpression_Attribute_initializedElement() const = 0;
			virtual std::shared_ptr<ecore::EReference> getOclExpression_Attribute_instance() const = 0;
			virtual std::shared_ptr<ecore::EReference> getOclExpression_Attribute_lastOwner() const = 0;
			virtual std::shared_ptr<ecore::EReference> getOclExpression_Attribute_loopBodyOwner() const = 0;
			virtual std::shared_ptr<ecore::EReference> getOclExpression_Attribute_parentCall() const = 0;
			virtual std::shared_ptr<ecore::EReference> getOclExpression_Attribute_parentNav() const = 0;
			virtual std::shared_ptr<ecore::EReference> getOclExpression_Attribute_thenOwner() const = 0;
			virtual std::shared_ptr<ecore::EReference> getOclExpression_Attribute_topExpression() const = 0;
			
			
			// End Class OclExpression


			// Begin Class OperationCallExp
			//Class and Feature IDs 
			static const unsigned int OPERATIONCALLEXP_CLASS = 65;
			static const unsigned int OPERATIONCALLEXP_CLASS_FEATURE_COUNT = 29;
			static const unsigned int OPERATIONCALLEXP_CLASS_OPERATION_COUNT = 16;
			
			static const int OPERATIONCALLEXP_ATTRIBUTE_ARGUMENT = 6527;
			static const int OPERATIONCALLEXP_ATTRIBUTE_REFERREDOPERATION = 6528;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getOperationCallExp_Class() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getOperationCallExp_Attribute_argument() const = 0;
			virtual std::shared_ptr<ecore::EReference> getOperationCallExp_Attribute_referredOperation() const = 0;
			
			
			// End Class OperationCallExp


			// Begin Class PrimitiveLiteralExp
			//Class and Feature IDs 
			static const unsigned int PRIMITIVELITERALEXP_CLASS = 69;
			static const unsigned int PRIMITIVELITERALEXP_CLASS_FEATURE_COUNT = 26;
			static const unsigned int PRIMITIVELITERALEXP_CLASS_OPERATION_COUNT = 16;
			static const int PRIMITIVELITERALEXP_ATTRIBUTE_SYMBOL = 6925;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getPrimitiveLiteralExp_Class() const = 0;
			
			virtual std::shared_ptr<ecore::EAttribute> getPrimitiveLiteralExp_Attribute_symbol() const = 0;
			
			
			
			// End Class PrimitiveLiteralExp


			// Begin Class PropertyCallExp
			//Class and Feature IDs 
			static const unsigned int PROPERTYCALLEXP_CLASS = 71;
			static const unsigned int PROPERTYCALLEXP_CLASS_FEATURE_COUNT = 30;
			static const unsigned int PROPERTYCALLEXP_CLASS_OPERATION_COUNT = 16;
			
			static const int PROPERTYCALLEXP_ATTRIBUTE_REFERREDPROPERTY = 7129;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getPropertyCallExp_Class() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getPropertyCallExp_Attribute_referredProperty() const = 0;
			
			
			// End Class PropertyCallExp


			// Begin Class RealLiteralExp
			//Class and Feature IDs 
			static const unsigned int REALLITERALEXP_CLASS = 73;
			static const unsigned int REALLITERALEXP_CLASS_FEATURE_COUNT = 27;
			static const unsigned int REALLITERALEXP_CLASS_OPERATION_COUNT = 16;
			static const int REALLITERALEXP_ATTRIBUTE_REALSYMBOL = 7326;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getRealLiteralExp_Class() const = 0;
			
			virtual std::shared_ptr<ecore::EAttribute> getRealLiteralExp_Attribute_realSymbol() const = 0;
			
			
			
			// End Class RealLiteralExp


			// Begin Class StateExp
			//Class and Feature IDs 
			static const unsigned int STATEEXP_CLASS = 79;
			static const unsigned int STATEEXP_CLASS_FEATURE_COUNT = 26;
			static const unsigned int STATEEXP_CLASS_OPERATION_COUNT = 16;
			
			static const int STATEEXP_ATTRIBUTE_REFERREDSTATE = 7925;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getStateExp_Class() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getStateExp_Attribute_referredState() const = 0;
			
			
			// End Class StateExp


			// Begin Class StringLiteralExp
			//Class and Feature IDs 
			static const unsigned int STRINGLITERALEXP_CLASS = 81;
			static const unsigned int STRINGLITERALEXP_CLASS_FEATURE_COUNT = 27;
			static const unsigned int STRINGLITERALEXP_CLASS_OPERATION_COUNT = 16;
			static const int STRINGLITERALEXP_ATTRIBUTE_STRINGSYMBOL = 8126;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getStringLiteralExp_Class() const = 0;
			
			virtual std::shared_ptr<ecore::EAttribute> getStringLiteralExp_Attribute_stringSymbol() const = 0;
			
			
			
			// End Class StringLiteralExp


			// Begin Class TupleLiteralExp
			//Class and Feature IDs 
			static const unsigned int TUPLELITERALEXP_CLASS = 84;
			static const unsigned int TUPLELITERALEXP_CLASS_FEATURE_COUNT = 26;
			static const unsigned int TUPLELITERALEXP_CLASS_OPERATION_COUNT = 16;
			
			static const int TUPLELITERALEXP_ATTRIBUTE_PART = 8425;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getTupleLiteralExp_Class() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getTupleLiteralExp_Attribute_part() const = 0;
			
			
			// End Class TupleLiteralExp


			// Begin Class TupleLiteralPart
			//Class and Feature IDs 
			static const unsigned int TUPLELITERALPART_CLASS = 87;
			static const unsigned int TUPLELITERALPART_CLASS_FEATURE_COUNT = 14;
			static const unsigned int TUPLELITERALPART_CLASS_OPERATION_COUNT = 16;
			
			static const int TUPLELITERALPART_ATTRIBUTE_ATTRIBUTE = 8713;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getTupleLiteralPart_Class() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getTupleLiteralPart_Attribute_attribute() const = 0;
			
			
			// End Class TupleLiteralPart


			// Begin Class TypeExp
			//Class and Feature IDs 
			static const unsigned int TYPEEXP_CLASS = 90;
			static const unsigned int TYPEEXP_CLASS_FEATURE_COUNT = 26;
			static const unsigned int TYPEEXP_CLASS_OPERATION_COUNT = 16;
			
			static const int TYPEEXP_ATTRIBUTE_REFERREDTYPE = 9025;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getTypeExp_Class() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getTypeExp_Attribute_referredType() const = 0;
			
			
			// End Class TypeExp


			// Begin Class UnlimitedNaturalExp
			//Class and Feature IDs 
			static const unsigned int UNLIMITEDNATURALEXP_CLASS = 92;
			static const unsigned int UNLIMITEDNATURALEXP_CLASS_FEATURE_COUNT = 27;
			static const unsigned int UNLIMITEDNATURALEXP_CLASS_OPERATION_COUNT = 16;
			static const int UNLIMITEDNATURALEXP_ATTRIBUTE_UNLIMITEDNATURALSYMBOL = 9226;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getUnlimitedNaturalExp_Class() const = 0;
			
			virtual std::shared_ptr<ecore::EAttribute> getUnlimitedNaturalExp_Attribute_unlimitedNaturalSymbol() const = 0;
			
			
			
			// End Class UnlimitedNaturalExp


			// Begin Class UnspecifiedValueExp
			//Class and Feature IDs 
			static const unsigned int UNSPECIFIEDVALUEEXP_CLASS = 94;
			static const unsigned int UNSPECIFIEDVALUEEXP_CLASS_FEATURE_COUNT = 25;
			static const unsigned int UNSPECIFIEDVALUEEXP_CLASS_OPERATION_COUNT = 16;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getUnspecifiedValueExp_Class() const = 0;
			
			
			
			
			// End Class UnspecifiedValueExp


			// Begin Class Variable
			//Class and Feature IDs 
			static const unsigned int VARIABLE_CLASS = 96;
			static const unsigned int VARIABLE_CLASS_FEATURE_COUNT = 22;
			static const unsigned int VARIABLE_CLASS_OPERATION_COUNT = 16;
			
			static const int VARIABLE_ATTRIBUTE_BASEEXP = 9616;
			static const int VARIABLE_ATTRIBUTE_INITEXPRESSION = 9613;
			static const int VARIABLE_ATTRIBUTE_LOOPEXP = 9615;
			static const int VARIABLE_ATTRIBUTE_REFERRINGEXP = 9617;
			static const int VARIABLE_ATTRIBUTE_REPRESENTEDPARAMETER = 9614;
			static const int VARIABLE_ATTRIBUTE_RESULTOWNER = 9619;
			static const int VARIABLE_ATTRIBUTE_SELFOWNER = 9618;
			static const int VARIABLE_ATTRIBUTE_VALUE = 9621;
			static const int VARIABLE_ATTRIBUTE_VAROWNER = 9620;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getVariable_Class() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getVariable_Attribute_baseExp() const = 0;
			virtual std::shared_ptr<ecore::EReference> getVariable_Attribute_initExpression() const = 0;
			virtual std::shared_ptr<ecore::EReference> getVariable_Attribute_loopExp() const = 0;
			virtual std::shared_ptr<ecore::EReference> getVariable_Attribute_referringExp() const = 0;
			virtual std::shared_ptr<ecore::EReference> getVariable_Attribute_representedParameter() const = 0;
			virtual std::shared_ptr<ecore::EReference> getVariable_Attribute_resultOwner() const = 0;
			virtual std::shared_ptr<ecore::EReference> getVariable_Attribute_selfOwner() const = 0;
			virtual std::shared_ptr<ecore::EReference> getVariable_Attribute_value() const = 0;
			virtual std::shared_ptr<ecore::EReference> getVariable_Attribute_varOwner() const = 0;
			
			
			// End Class Variable


			// Begin Class VariableExp
			//Class and Feature IDs 
			static const unsigned int VARIABLEEXP_CLASS = 98;
			static const unsigned int VARIABLEEXP_CLASS_FEATURE_COUNT = 26;
			static const unsigned int VARIABLEEXP_CLASS_OPERATION_COUNT = 16;
			
			static const int VARIABLEEXP_ATTRIBUTE_REFERREDVARIABLE = 9825;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getVariableExp_Class() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getVariableExp_Attribute_referredVariable() const = 0;
			
			
			// End Class VariableExp

			static const int COLLECTIONKIND_CLASS = 13;
			
			virtual std::shared_ptr<ecore::EEnum> getCollectionKind_Class() const = 0;
			

			

			//Singleton Instance and Getter
			private:
				static std::shared_ptr<ExpressionsPackage> instance;
			public:
				static std::shared_ptr<ExpressionsPackage> eInstance();
	};
}
#endif /* end of include guard: OCL_EXPRESSIONSPACKAGE_HPP */
