//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef OCL_EVALUATIONS_OCLEXPEVALOCLEXPEVALIMPL_HPP
#define OCL_EVALUATIONS_OCLEXPEVALOCLEXPEVALIMPL_HPP

//*********************************
// generated Includes

//Model includes
#include "../OclExpEval.hpp"

#include "ocl/Evaluations/impl/EvaluationsFactoryImpl.hpp"
#include "fUML/Semantics/Values/impl/EvaluationImpl.hpp"

//*********************************
namespace ocl::Evaluations 
{
	class OclExpEvalImpl :virtual public fUML::Semantics::Values::EvaluationImpl, virtual public OclExpEval 
	{
		public: 
			OclExpEvalImpl(const OclExpEvalImpl & obj);
			virtual std::shared_ptr<ecore::EObject> copy() const;

		private:    
			OclExpEvalImpl& operator=(OclExpEvalImpl const&) = delete;

		protected:
			friend class ocl::Evaluations::EvaluationsFactoryImpl;
			OclExpEvalImpl();
			virtual std::shared_ptr<OclExpEval> getThisOclExpEvalPtr() const;
			virtual void setThisOclExpEvalPtr(std::weak_ptr<OclExpEval> thisOclExpEvalPtr);



		public:
			//destructor
			virtual ~OclExpEvalImpl();
			
			//*********************************
			// Operations
			//*********************************
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			
			//*********************************
			// Reference
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<ocl::Evaluations::EvalEnvironment > getBeforeEnvironment() const ;
			
			/*!
			 */
			virtual void setBeforeEnvironment(std::shared_ptr<ocl::Evaluations::EvalEnvironment> _beforeEnvironment_beforeEnvironment) ;
			/*!
			 */
			virtual std::shared_ptr<ocl::Evaluations::EvalEnvironment > getEnvironment() const ;
			
			/*!
			 */
			virtual void setEnvironment(std::shared_ptr<ocl::Evaluations::EvalEnvironment> _environment_environment) ;
			/*!
			 */
			virtual std::shared_ptr<ocl::Expressions::OclExpression > getModel() const ;
			
			/*!
			 */
			virtual void setModel(std::shared_ptr<ocl::Expressions::OclExpression> _model_model) ;
			/*!
			 */
			virtual std::shared_ptr<fUML::Semantics::Values::Value > getResultValue() const ;
			
			/*!
			 */
			virtual void setResultValue(std::shared_ptr<fUML::Semantics::Values::Value> _resultValue_resultValue) ;
							
			
			//*********************************
			// Union Getter
			//*********************************
			 
			 
			//*********************************
			// Structural Feature Getter/Setter
			//*********************************

			virtual std::shared_ptr<ecore::EObject> eContainer() const ; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) ;
			virtual void loadAttributes(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::map<std::string, std::string> attr_list);
			virtual void loadNode(std::string nodeName, std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler);
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) ;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const ;
			virtual void saveContent(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const;
			

		protected:
			virtual std::shared_ptr<ecore::EClass> eStaticClass() const;
			virtual Any eGet(int featureID, bool resolve, bool coreType) const ;
			virtual bool internalEIsSet(int featureID) const ;
			virtual bool eSet(int featureID, Any newValue) ;

		private:
			std::weak_ptr<OclExpEval> m_thisOclExpEvalPtr;
	};
}
#endif /* end of include guard: OCL_EVALUATIONS_OCLEXPEVALOCLEXPEVALIMPL_HPP */
