//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef OCL_UTILITIESPACKAGE_HPP
#define OCL_UTILITIESPACKAGE_HPP

#include "ecore/EPackage.hpp"

namespace ecore 
{
}

namespace ocl::Utilities 
{

}

namespace ocl::Utilities 
{
	/*!
	The Metamodel Package for the Utilities metamodel. This package is used to enable the reflection of model elements. It contains all model elements
	which were described in an ecore file.
	*/
	/*!
	 */
	class UtilitiesPackage : virtual public ecore::EPackage 
	{
		private:    
			UtilitiesPackage(UtilitiesPackage const&) = delete;
			UtilitiesPackage& operator=(UtilitiesPackage const&) = delete;

		protected:
			UtilitiesPackage(){}

		public:
			//static variables
			static const std::string eNAME;
			static const std::string eNS_URI;
			static const std::string eNS_PREFIX;

			
			

			

			//Singleton Instance and Getter
			private:
				static std::shared_ptr<UtilitiesPackage> instance;
			public:
				static std::shared_ptr<UtilitiesPackage> eInstance();
	};
}
#endif /* end of include guard: OCL_UTILITIESPACKAGE_HPP */
